CREATE TABLE pessoa(
	id BIGINT(10) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	rua VARCHAR(100),
	bairro VARCHAR(50),
	numero int(10)	
)ENGINE=innoDB  DEFAULT CHARSET=utf8;

INSERT INTO pessoa(nome,rua,bairro,numero) VALUES ("HUGO MENEZES", "MARCILIO FARIAS", "AEROLÂNDIA", 2320);
INSERT INTO pessoa(nome,rua,bairro,numero) VALUES ("MARIA FARIAS", "PASTEUR", "PIRAMBU", 1000);
INSERT INTO pessoa(nome,rua,bairro,numero) VALUES ("HELENA CASTRO SILVA", "CORONEL ALMIRANTE FIILHO", "BOM JARDIM", 160);
INSERT INTO pessoa(nome,rua,bairro,numero) VALUES ("CARLOS BARBOSA DE FREITAS", "PROFESSOR ALBER JR", "BARRA DO CEARÁ", 1500);
INSERT INTO pessoa(nome,rua,bairro,numero) VALUES ("EMILY BRITTO", "CONDE DA ALVORADA", "JOQUIM TÁVORA", 020);
INSERT INTO pessoa(nome,rua,bairro,numero) VALUES ("JOSIAS DA SILVA", "AV CORONEL DE CARV", "ALDEOTA", 99975);
INSERT INTO pessoa(nome,rua,bairro,numero) VALUES ("MARCONDES", "J DA PENHA", "CENTRO", 10);
INSERT INTO pessoa(nome,rua,bairro,numero) VALUES ("MARILIA GABRILA VIREIRA", "JOSE BONIFACIO", "MESSEJANA", 1003);